<?php

namespace app\admin\service;

use app\common\model\Base;
use think\session;
class ArticleCategory extends Base
{
    use \traits\controller\Jump;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public $status
        = [
            1 => '启用',
            2 => '停用'
        ];

    /**
     * 数组组装校验--编辑
     * @author tangp
     * @date 2019-04-16
     */
    public function buildDataEdit()
    {
        return $this->buildDataAdd();
    }

    /**
     * 添加的数据校验
     * @return array|void
     */
    public function buildDataAdd()
    {
        $id     = input('post.id/d');
        $name  = input('post.name/s');
//        $status = input('post.status/d');
        $sort   = input('post.sort/d');
        if (empty($sort)) {
            $sort = 150;
        }
        if (empty($name)) {
            return $this->error('请输入文章分类名称！');
        }
        $arr = [
            'id'       => $id,
            'name'    => $name,
            'sort'     => $sort,
//            'status'   => $status,
            'add_time' => time(),
            'add_user' => session::get('user_auth.uid'),
        ];

        return $arr;
    }

    /**
     * 执行编辑
     * @param $arr
     * @author tangp
     * @date 2019-04-16
     * @return mixed
     */
    public function goEdit($arr)
    {
        $result = $this->edit($arr);
        if (false !== $result) {
            return $this->success("操作成功！", url('admin/ArticleCategory/index'));
        } else {
            return $this->error("操作失败！");
        }
    }

    /**
     * 删除
     * @author tangp
     * @date 2019-04-16
     * @param $id
     */
    public function goDrop($id)
    {
        $id_arr = explode(',',$id);
        foreach ($id_arr as $v){
            $result = $this->drop($v);
        }

        if (false !== $result) {
            return $this->success("操作成功！");
        } else {
            return $this->error("操作失败！");
        }
    }

    /**
     * 分类下拉框获取
     * @return array|void
     */
    public function getParentName()
    {
        $parent_name = $this->order('id disc')->field('id,name')->column('name', 'id');
        return $parent_name;
    }
}