<?php
/**
 * 员工审核模型
 * Created by PhpStorm.
 * User: cc
 * Date: 2017/8/19
 */
namespace app\common\model;

class UserVerify extends Base {

    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->is_cache = false;
    }
}